import { GoogleGenAI } from "@google/genai";

const IMAGEN_MODEL_NAME = "imagen-4.0-fast-generate-001";

interface GenerateImageRequest {
  prompt: string;
  aspectRatio: string;
}

export default async function handler(req: any, res: any) {
  // Set CORS headers
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET,OPTIONS,PATCH,DELETE,POST,PUT",
  );
  res.setHeader(
    "Access-Control-Allow-Headers",
    "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version",
  );

  // Handle OPTIONS request for CORS preflight
  if (req.method === "OPTIONS") {
    res.status(200).end();
    return;
  }

  // Only allow POST requests
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { prompt, aspectRatio }: GenerateImageRequest = req.body;

    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    if (!aspectRatio) {
      return res.status(400).json({ error: "Aspect ratio is required" });
    }

    // Get API key from environment variable (set in Vercel dashboard)
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      console.error("GEMINI_API_KEY environment variable is not set");
      return res
        .status(500)
        .json({ error: "API key is not configured on the server" });
    }

    const ai = new GoogleGenAI({ apiKey });

    // Use the correct API method for Imagen
    const imageResponse = await ai.models.generateImages({
      model: IMAGEN_MODEL_NAME,
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: "image/png",
        aspectRatio: aspectRatio,
      },
    });

    if (
      imageResponse &&
      imageResponse.generatedImages &&
      imageResponse.generatedImages.length > 0
    ) {
      const generatedImage = imageResponse.generatedImages[0];

      if (generatedImage.image && generatedImage.image.imageBytes) {
        const base64Image = generatedImage.image.imageBytes;
        return res.status(200).json({
          imageUrl: `data:image/png;base64,${base64Image}`,
          prompt: prompt,
        });
      } else {
        throw new Error("No image data returned from Gemini API");
      }
    } else {
      throw new Error("No images generated by Gemini API");
    }
  } catch (error: any) {
    console.error("Error generating image with Gemini API:", error);

    let errorMessage = "Failed to generate image";
    let statusCode = 500;

    if (error.message) {
      errorMessage = error.message;
    }

    if (error.status) {
      statusCode = error.status;
    }

    // Check for specific error types
    if (
      error.message?.toLowerCase().includes("quota") ||
      error.status === 429
    ) {
      errorMessage = "API quota exceeded. Please try again later.";
      statusCode = 429;
    } else if (error.message?.toLowerCase().includes("api key")) {
      errorMessage = "API key configuration error";
      statusCode = 401;
    }

    return res.status(statusCode).json({
      error: errorMessage,
      details:
        process.env.NODE_ENV === "development" ? error.message : undefined,
    });
  }
}
